# Used when specific branch for given repo does not exist.
default: develop

branches:
  # Specification of branches from which docker images list will be pulled.
  onezone: current_branch
  onedata: current_branch

  # Specification of branches from which sources for components will be pulled.
  oz-worker: current_branch
  op-worker: current_branch
  onepanel: current_branch
  cluster-manager: current_branch
