# Used when specific branch for given repo does not exist.
default: develop

branches:
  # Specification of branches from which docker images list will be pulled.
  # Onezone packages plan
  onezone: merge-19.09-to-develop
  # Oneprovider packages plan
  onedata: merge-19.09-to-develop
  oneclient_docker_build: merge-19.09-to-develop
  luma_docker_build: develop
  rest_cli_docker_build: develop

  # Specification of branches from which sources for components will be pulled.
  oz-worker: merge-19.09-to-develop
  op-worker: merge-19.09-to-develop
  onepanel: merge-19.09-to-develop
  cluster-manager: merge-19.09-to-develop
  oneclient: merge-19.09-to-develop
