# Used when specific branch for given repo does not exist.
default: develop

branches:
  # Specification of branches from which docker images list will be pulled.
  # Onezone packages plan
  onezone: release/19.09.0-alpha1
  # Oneprovider packages plan
  onedata: release/19.09.0-alpha1
  oneclient_docker_build: develop
  luma_docker_build: develop
  rest_cli_docker_build: develop

  # Specification of branches from which sources for components will be pulled.
  oz-worker: release/19.09.0-alpha1
  op-worker: release/19.09.0-alpha1
  onepanel: release/19.09.0-alpha1
  cluster-manager: release/19.09.0-alpha1
  oneclient: develop