# Used when specific branch for given repo does not exist.
default: release/19.02.1

branches:
  # Specification of branches from which docker images list will be pulled.
  # Onezone packages plan
  onezone: current_branch
  # Oneprovider packages plan
  onedata: current_branch
  oneclient_docker_build: current_branch
  luma_docker_build: develop
  rest_cli_docker_build: develop

  # Specification of branches from which sources for components will be pulled.
  oz-worker: release/19.09.0-alpha1
  op-worker: release/19.09.0-alpha1
  onepanel: release/19.09.0-alpha1
  cluster-manager: release/19.09.0-alpha1
  oneclient: current_branch