# Used when specific branch for given repo does not exist.
default: develop

branches:
  # Specification of branches from which docker images list will be pulled.
  onezone-pkg: develop
  oneprovider-pkg: develop
  oneclient_docker_build: develop
  rest_cli_docker_build: develop

  # Specification of branches from which sources for components will be pulled.
  oz-worker: develop
  op-worker: develop
  onepanel: develop
  cluster-manager: develop
  oneclient: develop
