# Used when specific branch for given repo does not exist.
default: develop

images:
  # Specification of branches from which docker images will be pulled.
  onezone: develop
  oneprovider: current_branch
  oneclient: develop
  rest-cli: default
  openfaas-pod-status-monitor: develop
  openfaas-lambda-result-streamer: develop

sources:
  # Specification of branches from which sources for components will be pulled.
  oz-worker: develop
  op-worker: current_branch
  onepanel: develop
  cluster-manager: develop
  oneclient: develop
