# Used when specific branch for given repo does not exist.
default: develop

images:
  # Specification of branches from which docker images will be pulled.
  onezone: current_branch
  oneprovider: current_branch
  oneclient: current_branch
  rest-cli: default
  openfaas-pod-status-monitor: current_branch
  openfaas-lambda-result-streamer: current_branch

sources:
  # Specification of branches from which sources for components will be pulled.
  oz-worker: current_branch
  op-worker: feature-VFS-12133-block-modifying-operations-on-special-dirs
  onepanel: current_branch
  cluster-manager: current_branch
  oneclient: current_branch
