# Used when specific branch for given repo does not exist.
default: release/18.07.0-alpha

branches:
  # Specification of branches from which docker images list will be pulled.
  # Onezone packages plan
  onezone: feature/VFS-4751-federated-login-in-onepanel
  # Oneprovider packages plan
  onedata: feature/VFS-4751-federated-login-in-onepanel
  oneclient_docker_build: current_branch
  luma_docker_build: current_branch
  rest_cli_docker_build: current_branch

  # Specification of branches from which sources for components will be pulled.
  oz-worker: feature/VFS-4751-federated-login-in-onepanel
  op-worker: feature/VFS-4751-federated-login-in-onepanel
  onepanel: feature/VFS-4751-federated-login-in-onepanel
  cluster-manager: current_branch
  oneclient: current_branch