# Used when specific branch for given repo does not exist.
default: release/21.02.0-alpha25

branches:
  # Specification of branches from which docker images list will be pulled.
  onezone-pkg: current_branch
  oneprovider-pkg: current_branch
  oneclient_docker_build: current_branch
  rest_cli_docker_build: develop

  # Specification of branches from which sources for components will be pulled.
  oz-worker: current_branch
  op-worker: current_branch
  onepanel: current_branch
  cluster-manager: current_branch
  oneclient: current_branch
