version: 2
plan:
  project-key: ODSRV
  key: MAOPT
  name: mixed acceptance pkg
  description: Acceptance tests using different clients concurrently. Environment deployed from packages.
repositories:
  - onedata-acceptance:
      scope: global
branches:
  create:
    for-new-branch: release/.*
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
  link-to-jira: true
notifications:
  - events:
      - plan-failed
    recipients:
      - users:
          - plgjliput
labels: []
triggers: []
dependencies:
  require-all-stages-passing: true
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: "3"
  all-other-apps:
    custom:
      com.atlassian.bamboo.plugin.hungbuildkiller:
        stopped.enabled: "true"
        add_comment_when_hung.enabled: "true"
      buildExpiryConfig:
        period: weeks
        expiryTypeBuildLog: "true"
        enabled: "true"
        expiryTypeArtifact: "true"
        duration: "1"

stages:
  - Acceptance Test:
      manual: false
      final: false
      jobs:
        - _Codetag Tracker
        - Access tokens
        - Access tokens id caveats
        - Access tokens path caveats
        - ACL one entry
        - ACL two entries
        - Archive privileges
        - Archives 
        - Create file 
        - Datasets 
        - Directories movement 
        - Directories multi 
        - Directories remove metadata
        - Directories set metadata
        - Directories times 
        - File content 
        - Files movement 
        - Files multi 
        - Files remove metadata
        - Files set metadata
        - Files times 
        - Groups basic 
        - LUMA 
        - Nested directories create
        - Nested directories remove
        - Onepanel 
        - Permission POSIX 
        - Permission POSIX multi 
        - QoS 
        - Remove file 
        - Rename file 
        - Single directory 
        - Single directory 2
        - Spaces basic 
        - Storage sync
        - Tokens 

_Codetag Tracker:
  key: CDTR
  other: &common-opts
    clean-working-dir: true
    all-other-apps:
      custom:
        auto: {}
        clover:
          useLocalLicenseKey: "true"
        buildHangingConfig.enabled: "false"
  tasks:
    - checkout: &checkout-default-repository
        path: onedata-acceptance
        force-clean-build: "true"
        description: Checkout Default Repository
    - script: &init-submodules
        scripts:
          - |-
            git remote set-url origin ${bamboo.repository.git.repositoryUrl}
            git remote -v
            make submodules
        working-dir: onedata-acceptance
        description: Init submodules
    - script:
        working-dir: onedata-acceptance
        scripts:
          - make codetag-tracker BRANCH=${bamboo.planRepository.branchName}
        description: Codetag Tracker
  requirements: []
  artifact-subscriptions: []

Access tokens: &acceptance-mixed-tests-in-chrome-job
  key: CLT
  other: *common-opts
  tasks:
    - script: &clear-env
        scripts:
          - curl ${bamboo.OnedataFinalTasksURL} | bash -
        description: Clear env
    - script: &restart-minikube
        scripts:
          - sudo ${HOME}/restart_minikube.sh
        description: Restart minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: &download-artifacts
        scripts:
          - one_env/onenv pull_artifacts --hostname ${bamboo.artifactRepoHostname} --port ${bamboo.artifactRepoPort} --packages-only branchConfig.yaml
        working-dir: onedata-acceptance
        description: Download artifacts
    - script: &build-swaggers
        scripts:
          - make build_swaggers
        working-dir: onedata-acceptance
        description: Build swaggers
    - script: &run-acceptance-tests
        scripts:
          - make SUITE=test_access_tokens test_mixed_pkg
        working-dir: onedata-acceptance
        description: Run acceptance mixed tests in Chrome
  final-tasks:
    - test-parser:
        type: junit
        ignore-time: "false"
        test-results: onedata-acceptance/test-reports/results*.xml
        description: Parse test results
    - script:
        scripts:
          - |-
            cp onedata-acceptance/test-reports/*.xml onedata-acceptance/tests/mixed/logs
            cp onedata-acceptance/one_env/sources_info.yaml onedata-acceptance/tests/mixed/logs
            mv onedata-acceptance/tests/mixed/logs/report.* onedata-acceptance/tests/mixed/logs/gui_report
            mv onedata-acceptance/tests/mixed/logs/gui_report/images.yaml onedata-acceptance/tests/mixed/logs
        description: Pack logs
    - script:
        <<: *clear-env
        working-dir: onedata-acceptance
        description: Clear env and working dir
  artifacts:
    - name: report
      location: onedata-acceptance/tests/mixed/logs/
      pattern: "**/*.*"
      shared: false
      required: false
  requirements:
    - minikube
  artifact-subscriptions: []

Access tokens id caveats:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CATIC
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_access_tokens_id_caveats test_mixed_pkg

Access tokens path caveats:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CATPC
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_access_tokens_path_caveats test_mixed_pkg

ACL one entry:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CAOE
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_acl_one_entry test_mixed_pkg

ACL two entries:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CATE
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_acl_two_entries test_mixed_pkg

Archive privileges:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CAP
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_archive_privileges test_mixed_pkg

Archives:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CAT3
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_archives test_mixed_pkg

Create file:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CCFT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_create_file test_mixed_pkg

Datasets:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_dataset test_mixed_pkg

Directories movement:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDMT2
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_directories_movement test_mixed_pkg

Directories multi:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDMT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_directories_multi ENV_FILE=1oz_1op_2oc test_mixed_pkg

Directories remove metadata:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDRM
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_directories_remove_metadata test_mixed_pkg

Directories set metadata:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDSM
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_directories_set_metadata test_mixed_pkg

Directories times:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDTT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_directories_times test_mixed_pkg

File content:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CFCT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_file_content test_mixed_pkg

Files movement:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CFMT2
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_files_movement test_mixed_pkg

Files multi:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CFMT3
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_files_multi ENV_FILE=1oz_1op_2oc test_mixed_pkg

Files remove metadata:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CFRM
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_files_remove_metadata test_mixed_pkg

Files set metadata:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CFSM
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_files_set_metadata test_mixed_pkg

Files times:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CFTT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_files_times test_mixed_pkg

Groups basic:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CGBT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_groups_basic test_mixed_pkg

LUMA:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CATC
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make ENV_FILE=1oz_1op_luma_oneclient SUITE=test_luma test_mixed_pkg

Nested directories create:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CNDC
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_nested_directories_create test_mixed_pkg

Nested directories remove:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CNDR
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_nested_directories_remove test_mixed_pkg

Onepanel:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: COT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_onepanel_basic test_mixed_pkg

Permission POSIX multi:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CPPMT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_permission_posix_multi ENV_FILE=1oz_1op_2oc test_mixed_pkg

Permission POSIX:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CPPT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_permission_posix test_mixed_pkg

QoS:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CQT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_qos test_mixed_pkg

Remove file:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CRFT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_remove_file test_mixed_pkg

Rename file:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CRFT1
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_rename_file test_mixed_pkg

Single directory 2:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CSDT2
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_single_directory2 test_mixed_pkg

Single directory:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CDBT2
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_single_directory test_mixed_pkg

Spaces basic:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CSBT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_spaces_basic test_mixed_pkg

Storage sync:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CSS
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_storage_sync test_mixed_pkg

Tokens:
  <<: *acceptance-mixed-tests-in-chrome-job
  key: CTT
  tasks:
    - script: *clear-env
    - script: *restart-minikube
    - checkout: *checkout-default-repository
    - script: *init-submodules
    - script: *download-artifacts
    - script: *build-swaggers
    - script:
        <<: *run-acceptance-tests
        scripts:
          - make SUITE=test_tokens test_mixed_pkg
